/* Deterministic offline rendering: frame number / fps drives every animation. */
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const{chromium}=require('/Users/acemetric/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),python=path.resolve(root,'../工具/.venv/bin/python');
const ffmpeg=cp.execFileSync(python,['-c','import imageio_ffmpeg; print(imageio_ffmpeg.get_ffmpeg_exe())'],{encoding:'utf8'}).trim();
const only=process.argv[2]||'both';
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:18790/'+encodeURI('宣传片/动画/动态样片.html'));await page.waitForFunction(()=>window.movieReady,{timeout:60000});
 for(const mode of only==='both'?['new','baseline']:[only]){const target=path.join(root,'输出',mode==='new'?'更迭-插画电影化样片-v1.mp4':'原版效果-对照.mp4');const args=['-y','-hide_banner','-loglevel','warning','-f','image2pipe','-vcodec','png','-framerate','30','-i','pipe:0','-i',path.join(root,'输出/样片混音.wav'),'-map','0:v:0','-map','1:a:0','-frames:v','540','-c:v','libx264','-preset','medium','-crf','18','-pix_fmt','yuv420p','-c:a','aac','-b:a','256k','-movflags','+faststart','-t','18',target];const enc=cp.spawn(ffmpeg,args,{stdio:['pipe','ignore','pipe']});let stderr='';enc.stderr.on('data',d=>stderr+=d);const completion=new Promise((resolve,reject)=>enc.on('close',code=>code?reject(Error('Encoder '+code+': '+stderr)):resolve()));enc.stdin.on('error',()=>{});const started=Date.now();for(let frame=0;frame<540;frame++){const data=await page.evaluate(async({frame,mode})=>{await promoMovie.render(frame/30,{mode});return promoMovie.canvas.toDataURL('image/png');},{frame,mode});const buffer=Buffer.from(data.split(',')[1],'base64');if(!enc.stdin.write(buffer))await new Promise(r=>enc.stdin.once('drain',r));if(frame%90===0)console.log(JSON.stringify({mode,frame,total:540,elapsed:Math.round((Date.now()-started)/1000)}));}enc.stdin.end();await completion;console.log(JSON.stringify({mode,output:target,seconds:(Date.now()-started)/1000,errors}));}
 await browser.close();if(errors.length)throw Error(errors.join('\n'));})().catch(e=>{console.error(e);process.exitCode=1;});
