const fs=require('node:fs'),path=require('node:path');const{chromium}=require('/Users/acemetric/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[],bad=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)bad.push({url:r.url(),status:r.status()});});await page.goto('http://127.0.0.1:18790/'+encodeURI('宣传片/动画/动态样片.html'));await page.waitForFunction(()=>window.movieReady,{timeout:60000});
 const checks=await page.evaluate(async()=>{const deterministic=[];for(const t of [2.2,8.2,15.2]){await promoMovie.render(t);const a=promoMovie.canvas.toDataURL();await promoMovie.render(4.1);await promoMovie.render(10.3);await promoMovie.render(t);deterministic.push({t,repeatable:a===promoMovie.canvas.toDataURL()});}await promoMovie.render(15);const withText=promoMovie.canvas.toDataURL();await promoMovie.render(15,{text:false});const withoutText=promoMovie.canvas.toDataURL();await promoMovie.render(15,{effects:false});const noFX=promoMovie.canvas.toDataURL();await promoMovie.render(15,{mode:'baseline'});const old=promoMovie.canvas.toDataURL();await promoMovie.render(15,{mode:'baseline',text:false});const oldWithoutText=promoMovie.canvas.toDataURL();const response=await fetch('输出/样片混音.wav'),ac=new AudioContext();const b=await ac.decodeAudioData(await response.arrayBuffer());await ac.close();return{deterministic,textToggle:withText!==withoutText,effectToggle:withText!==noFX,baselineDifferent:old!==withText,baselineTextToggle:old!==oldWithoutText,audio:{duration:b.duration,sampleRate:b.sampleRate,channels:b.numberOfChannels},fonts:document.fonts.check('700 70px SourceHan')};});
 await page.evaluate(()=>movieUI.seek(7));await page.locator('#next').click();const next=await page.evaluate(()=>movieUI.getTime());await page.locator('#prev').click();const prev=await page.evaluate(()=>movieUI.getTime());await page.locator('[data-t="12"]').click();const segmentSeek=await page.evaluate(()=>movieUI.getTime());
 await page.locator('#sound').uncheck();await page.evaluate(()=>movieUI.seek(0));const start=Date.now();await page.locator('#play').click();await page.waitForTimeout(1300);await page.locator('#play').click();const played=await page.evaluate(()=>movieUI.getTime());const elapsed=(Date.now()-start)/1000;const clockStable=played>.85&&played<elapsed+.15;
 const metadata=[];for(const file of ['更迭-插画电影化样片-v1.mp4','更迭-动画升级对比-v1.mp4']){const m=await page.evaluate(async file=>{const video=document.createElement('video');video.muted=true;video.src='输出/'+file;document.body.append(video);await new Promise((resolve,reject)=>{video.onloadedmetadata=resolve;video.onerror=()=>reject(Error('Video decode failed'));});const info={file,width:video.videoWidth,height:video.videoHeight,duration:video.duration};video.currentTime=14;await new Promise(r=>video.onseeked=r);await video.play();const decoded=await new Promise(r=>video.requestVideoFrameCallback((now,meta)=>r(meta)));video.pause();info.decodedMediaTime=decoded.mediaTime;const c=document.createElement('canvas');c.width=960;c.height=540;c.getContext('2d').drawImage(video,0,0,960,540);info.frame=c.toDataURL('image/png');video.remove();return info;},file);fs.writeFileSync(path.join(root,'记录',file.replace('.mp4','-解码检查.png')),Buffer.from(m.frame.split(',')[1],'base64'));delete m.frame;metadata.push(m);}
 await page.evaluate(()=>movieUI.seek(14.8));await page.screenshot({path:path.join(root,'记录/预览页面.png'),fullPage:true});
 const passed=checks.deterministic.every(v=>v.repeatable)&&checks.textToggle&&checks.effectToggle&&checks.baselineDifferent&&checks.baselineTextToggle&&Math.abs(checks.audio.duration-18)<2/checks.audio.sampleRate&&checks.fonts&&Math.abs(next-7-1/30)<1e-6&&prev===7&&segmentSeek===12&&clockStable&&metadata.every(v=>v.width===1920&&v.height===1080&&Math.abs(v.duration-18)<.05&&Math.abs(v.decodedMediaTime-14)<.15)&&!errors.length&&!bad.length;
 const record={...checks,frameControls:{next,prev,segmentSeek},clock:{played,elapsed,passed:clockStable},metadata,errors,bad,passed};fs.writeFileSync(path.join(root,'记录/浏览器验收.json'),JSON.stringify(record,null,2)+'\n');console.log(JSON.stringify(record));await browser.close();if(!passed)process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1;});
