(async function(){
  const params=new URLSearchParams(location.search);
  let current=PROMO_PACK.shots.find(s=>s.id===params.get('shot'))||PROMO_PACK.shots[0],playing=false,fxPlaying=false,fxKind='fire',variant=false;
  const frame=document.getElementById('frame'),fx=document.getElementById('fxFrame');
  const byId=Object.fromEntries(PROMO_PACK.assets.map(a=>[a.id,a]));
  function assetURL(a){return a.path.startsWith('宣传片/')?a.path.slice(4):'../'+a.path;}
  function available(a){return a.kind==='original'||a.status.startsWith('已制作');}
  function references(){const host=document.getElementById('references');host.replaceChildren();const title=document.createElement('p');title.className='description';title.textContent='原图参考 · 完整卡面与独立透明配图';host.append(title);const list=document.createElement('div');list.className='reference-list';for(const src of [...current.cards,...(current.cutouts||[])]){const a=document.createElement('a');a.href=src;a.target='_blank';a.className='checker';const img=document.createElement('img');img.src=src;img.alt=decodeURIComponent(src.split('/').pop());a.append(img);list.append(a);}host.append(list);}
  async function render(){const shot={...current};if(current.id==='04'&&variant&&available(byId['BG-04B'])){shot.scenePath=assetURL(byId['BG-04B']);shot.cards=['../卡牌/奇观/时代1/莫高窟.jpg'];}await PromoFrame.render(frame,shot,{progress:Number(document.getElementById('progress').value),effects:document.getElementById('effectsToggle').checked,showCards:document.getElementById('cardsToggle').checked});}
  async function selectShot(s){playing=false;current=s;variant=false;document.getElementById('play').textContent='播放效果';document.querySelectorAll('[data-shot]').forEach(b=>b.classList.toggle('active',b.dataset.shot===s.id));document.getElementById('variant').hidden=s.id!=='04'||!available(byId['BG-04B']);document.getElementById('variant').textContent='切换莫高窟';document.getElementById('shotMeta').textContent=`镜头 ${s.id} · ${s.name} · ${s.status} · 文字与真实卡面独立排版`;references();await render();}
  for(const s of PROMO_PACK.shots){const b=document.createElement('button');b.dataset.shot=s.id;b.textContent=s.id+' · '+s.name;const status=document.createElement('small');status.textContent=s.status;b.append(status);b.onclick=()=>selectShot(s);document.getElementById('shotList').append(b);}
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.tab==='effects')renderFX();});
  for(const id of ['progress','effectsToggle','cardsToggle'])document.getElementById(id).addEventListener('input',render);
  document.getElementById('play').onclick=()=>{playing=!playing;document.getElementById('play').textContent=playing?'暂停':'播放效果';if(playing)animate();};
  document.getElementById('variant').onclick=()=>{variant=!variant;document.getElementById('variant').textContent=variant?'切换金字塔':'切换莫高窟';references();if(variant){const a=document.querySelector('#references a');a.href='../卡牌/奇观/时代1/莫高窟.jpg';a.querySelector('img').src=a.href;}render();};
  async function animate(){if(!playing)return;const input=document.getElementById('progress');input.value=(Number(input.value)+.003)%1;await render();requestAnimationFrame(animate);}
  function tile(a){const f=document.createElement('figure');f.className='tile';const slot=document.createElement('div');slot.className='image';if(a.kind==='text'||a.kind==='effect'||a.kind==='layer'||a.kind==='cutout')slot.classList.add('checker');if(available(a)&&a.kind!=='audio'){const link=document.createElement('a');link.href=assetURL(a);link.target='_blank';const img=document.createElement('img');img.src=assetURL(a);img.alt=a.name;img.loading='lazy';link.append(img);slot.append(link);}else{const label=document.createElement('span');label.className='pending';label.textContent=a.status;slot.append(label);}const cap=document.createElement('figcaption');const title=document.createElement('h3');title.textContent=a.id+' · '+a.name;const desc=document.createElement('p');desc.textContent=a.description||a.status;const size=document.createElement('p');size.textContent=a.width?`${a.width}×${a.height}`:a.shots?'镜头 '+a.shots.join('、'):a.era||'';cap.append(title,desc,size);if(available(a)){const link=document.createElement('a');link.href=assetURL(a);link.target='_blank';link.textContent='打开资源';cap.append(link);}f.append(slot,cap);return f;}
  function assets(){const kind=document.getElementById('assetKind').value,q=document.getElementById('search').value.trim();const container=document.getElementById('assetTiles');container.replaceChildren();PROMO_PACK.assets.filter(a=>a.kind!=='audio'&&(kind==='all'||a.kind===kind)&&(a.id+a.name).includes(q)).forEach(a=>container.append(tile(a)));}
  document.getElementById('assetKind').onchange=assets;document.getElementById('search').oninput=assets;assets();
  for(const a of PROMO_PACK.assets.filter(a=>a.kind==='audio')){const f=tile(a);f.querySelector('.image').remove();if(available(a)){const audio=document.createElement('audio');audio.controls=true;audio.preload='none';audio.src=assetURL(a);f.querySelector('figcaption').append(audio);}document.getElementById('audioTiles').append(f);}
  async function renderFX(){const ctx=fx.getContext('2d');ctx.fillStyle='#13253a';ctx.fillRect(0,0,1920,1080);const p=Number(document.getElementById('fxProgress').value);if(fxKind==='cards'){for(let i=0;i<3;i++){const image=await PromoFrame.load('../卡牌/资源/'+['金币1.png','人力1.png','矿物1.png'][i]);const o=PromoEffects.cardOffset(i,p);ctx.save();ctx.globalAlpha=o.alpha;PromoFrame.contain(ctx,image,510+i*330+o.x,360+o.y,230,370);ctx.restore();}}PromoEffects.render(ctx,1920,1080,fxKind,p);document.getElementById('fxDownload').href='素材/效果/FX-'+fxKind+'.png';}
  for(const [kind,name]of [['fire','火光与火星'],['atmosphere','光照与空间气氛'],['cards','卡牌与资源运动'],['network','信息连接'],['stars','星辰与航迹']]){const b=document.createElement('button');b.textContent=name;b.dataset.fx=kind;b.onclick=()=>{fxKind=kind;document.querySelectorAll('[data-fx]').forEach(x=>x.classList.toggle('active',x===b));renderFX();};document.getElementById('fxList').append(b);}
  document.getElementById('fxProgress').oninput=renderFX;document.getElementById('fxPlay').onclick=()=>{fxPlaying=!fxPlaying;document.getElementById('fxPlay').textContent=fxPlaying?'暂停':'播放';if(fxPlaying)fxLoop();};async function fxLoop(){if(!fxPlaying)return;const p=document.getElementById('fxProgress');p.value=(Number(p.value)+.003)%1;await renderFX();requestAnimationFrame(fxLoop);}
  const layers=PROMO_PACK.assets.filter(a=>a.kind==='layer');const allLayers=layers.every(available);document.getElementById('layerNote').textContent=allLayers?'按深空、地球、飞船的顺序拼合。切换各层检查背景补全和透明边缘。':'透明图层尚在制作，完成后可在此检查拼合；当前镜头采用整图预览。';for(const a of layers){if(!available(a))continue;const image=document.createElement('img');image.src=assetURL(a);image.alt=a.name;document.getElementById('layerStage').append(image);const label=document.createElement('label'),checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=true;checkbox.onchange=()=>image.hidden=!checkbox.checked;label.append(checkbox,document.createTextNode(' '+a.name));document.getElementById('layerControls').append(label);}
  window.promoExport={renderLayers:async()=>{const canvas=document.createElement('canvas');canvas.width=1920;canvas.height=1080;const ctx=canvas.getContext('2d');for(const a of layers){ctx.drawImage(await PromoFrame.load(assetURL(a)),0,0,1920,1080);}return canvas.toDataURL('image/png');},renderShot:async(id,options={})=>{const shot={...PROMO_PACK.shots.find(s=>s.id===id)};if(id==='04'&&options.variant==='mogao'&&available(byId['BG-04B'])){shot.scenePath=assetURL(byId['BG-04B']);shot.cards=['../卡牌/奇观/时代1/莫高窟.jpg'];}await PromoFrame.render(frame,shot,options);return frame.toDataURL('image/png');},renderEffect:async(kind,p=.6)=>{const canvas=document.createElement('canvas');canvas.width=1920;canvas.height=1080;PromoEffects.render(canvas.getContext('2d'),1920,1080,kind,p,20261009);return canvas.toDataURL('image/png');}};
  await selectShot(current);if(params.has('tab'))document.querySelector(`[data-tab="${CSS.escape(params.get('tab'))}"]`)?.click();window.promoReady=true;
})();
