import {PIXEL_SCALE,RENDER_WIDTH,RENDER_HEIGHT} from './renderQuality.js';
import React,{useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {staticFile,delayRender,continueRender,cancelRender} from 'remotion';
import tracking from './tracking.json';import {smooth,editConfig,cameraProgress} from './transitions.js';
export const handleURL=(id,edge,k,suffix='.jpg')=>staticFile(`transitions/motion/${id}-${edge}/${String(k).padStart(3,'0')}${suffix}`);
const images=new Map();function fetchImage(url){if(!images.has(url))images.set(url,new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('Image '+url));im.src=url}));const result=images.get(url);images.delete(url);images.set(url,result);while(images.size>24)images.delete(images.keys().next().value);return result}
export function useImages(urls){const key=urls.join('|'),request=useMemo(()=>({handle:delayRender('跟踪遮罩与背景修补'),key}),[key]),[data,setData]=useState(null);useEffect(()=>{let alive=true;Promise.all(urls.map(fetchImage)).then(im=>{if(alive)setData({key,im});else continueRender(request.handle)}).catch(cancelRender);return()=>{alive=false;continueRender(request.handle)}},[key]);useLayoutEffect(()=>{if(data?.key===key)continueRender(request.handle)},[data,key]);return data?.key===key?data.im:null}
const center=pts=>pts.reduce((s,v)=>[s[0]+v[0]/pts.length,s[1]+v[1]/pts.length],[0,0]);
const radius=(pts,c)=>Math.sqrt(pts.reduce((s,v)=>s+(v[0]-c[0])**2+(v[1]-c[1])**2,0)/pts.length);
const lerp=(a,b,p)=>a+(b-a)*p;
export function trackAt(track,f){f=Math.max(0,Math.min(track.frames.length-1,f));const a=Math.floor(f),b=Math.min(a+1,track.frames.length-1),t=f-a;return track.frames[a].points.map((v,i)=>v.map((n,j)=>lerp(n,track.frames[b].points[i][j],t)))}
export function bridgeData(bridge){const into=bridge.type==='into',edge=into?'tail':'head',track=tracking[bridge.s.id+'-'+edge],p=bridge.local/(bridge.frames-1),points=trackAt(track,bridge.local),factor=into?1-cameraProgress(bridge,p):cameraProgress(bridge,p),print=into?smooth(...bridge.blend,p):1-smooth(...bridge.blend,p);return{into,edge,track,p,points,factor,print,key:track.card,uv:track.uv,subject:bridge.subject,shutterViews:Array.from({length:editConfig.motionSamples},(_,i)=>{const f=Math.max(0,bridge.local-editConfig.shutterAngle/360*i/(editConfig.motionSamples-1)),q=f/(bridge.frames-1);return{points:trackAt(track,f),factor:into?1-cameraProgress(bridge,q):cameraProgress(bridge,q)}})}}
function mesh(ctx,im,src,dest,tri,coordinateSize){for(const ids of tri){const[a,b,c]=ids.map(i=>src[i].map((v,j)=>v*(j===0?im.naturalWidth:im.naturalHeight)/coordinateSize[j])),[u,v,w]=ids.map(i=>dest[i]);const det=(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);if(Math.abs(det)<.001)continue;const ax=((v[0]-u[0])*(c[1]-a[1])-(w[0]-u[0])*(b[1]-a[1]))/det,bx=((w[0]-u[0])*(b[0]-a[0])-(v[0]-u[0])*(c[0]-a[0]))/det,ay=((v[1]-u[1])*(c[1]-a[1])-(w[1]-u[1])*(b[1]-a[1]))/det,by=((w[1]-u[1])*(b[0]-a[0])-(v[1]-u[1])*(c[0]-a[0]))/det;ctx.save();ctx.beginPath();const mid=[(u[0]+v[0]+w[0])/3,(u[1]+v[1]+w[1])/3];[u,v,w].forEach((p,i)=>{const d=Math.hypot(p[0]-mid[0],p[1]-mid[1]),q=p.map((n,j)=>n+(n-mid[j])*.45/Math.max(1,d));i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.closePath();ctx.clip();ctx.transform(ax,ay,bx,by,u[0]-ax*a[0]-bx*a[1],u[1]-ay*a[0]-by*a[1]);ctx.drawImage(im,0,0);ctx.restore()}}
export function destination(bridge,data,base,phase){const p=Math.max(0,Math.min(1,phase/(bridge.frames-1))),pts=trackAt(data.track,phase),c=center(base),d=center(pts),r=radius(pts,d),r0=radius(base,c),f=data.into?1-cameraProgress(bridge,p):cameraProgress(bridge,p),z=Math.exp(Math.log(r/Math.max(1,r0))*f),at=c.map((n,i)=>lerp(n,d[i],f)),target=base.map(v=>v.map((n,i)=>(n-c[i])*z+at[i])),tc=center(target),tr=radius(target,tc),shape=data.into?smooth(...bridge.shape,p):1-smooth(...bridge.shape,p);
 return pts.map((v,i)=>v.map((n,j)=>lerp(tc[j]+(n-d[j])*tr/r,target[i][j],shape)))}
export function CinematicBridge({bridge,source,base,data}){const ref=useRef(),sample=useMemo(()=>{const c=document.createElement("canvas");c.width=RENDER_WIDTH;c.height=RENDER_HEIGHT;return c},[]),layer=useMemo(()=>{const c=document.createElement("canvas");c.width=RENDER_WIDTH;c.height=RENDER_HEIGHT;return c},[]),im=useImages([handleURL(bridge.s.id,data.edge,bridge.local),handleURL(bridge.s.id,data.edge,bridge.local,'-bg.jpg'),handleURL(bridge.s.id,data.edge,bridge.local,'-fg.png')]);
 useLayoutEffect(()=>{if(!im)return;const ctx=ref.current.getContext('2d'),p=data.p;ctx.setTransform(PIXEL_SCALE,0,0,PIXEL_SCALE,0,0);ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';ctx.drawImage(source,0,0,1920,1080);const env=data.into?1-smooth(...bridge.environment,p):smooth(...bridge.environment,p);ctx.globalAlpha=env;ctx.drawImage(im[1],0,0,1920,1080);
 // Original plate at the native endpoints prevents repair halos entering/exiting the edit.
 const endpoint=data.into?1-smooth(0,.15,p):smooth(.85,1,p);ctx.globalAlpha=env*endpoint;ctx.drawImage(im[0],0,0,1920,1080);
 const fg=data.into?1-smooth(...bridge.blend,p):smooth(...bridge.blend,p),samples=editConfig.motionSamples,shutter=editConfig.shutterAngle/360;
 // The silhouette and camera use the same directional 180 degree shutter; no uniform blur.
 const lc=layer.getContext('2d');lc.setTransform(PIXEL_SCALE,0,0,PIXEL_SCALE,0,0);lc.clearRect(0,0,1920,1080);lc.globalCompositeOperation='lighter';for(let i=0;i<samples;i++){const at=Math.max(0,bridge.local-shutter*i/(samples-1)),dest=destination(bridge,data,base,at);const sc=sample.getContext('2d');sc.setTransform(PIXEL_SCALE,0,0,PIXEL_SCALE,0,0);sc.clearRect(0,0,1920,1080);sc.globalAlpha=1;sc.globalCompositeOperation='source-over';mesh(sc,im[2],data.points,dest,data.track.triangles,data.track.coordinateSize??[1920,1080]);lc.globalAlpha=fg/samples;lc.drawImage(sample,0,0,1920,1080)}ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1;ctx.drawImage(layer,0,0,1920,1080);window.hybridReady=true;window.bridgeProof={pair:bridge.pair,phase:bridge.local,points:destination(bridge,data,base,bridge.local),cameraFactor:data.factor};},[im,source,base,bridge.local]);
 return <canvas ref={ref} width={RENDER_WIDTH} height={RENDER_HEIGHT} style={{position:'absolute',width:'100%',height:'100%'}}/>}
