import {RENDER_WIDTH,RENDER_HEIGHT} from './renderQuality.js';
import React,{useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {AbsoluteFill,Audio,Img,OffthreadVideo,Sequence,Freeze,staticFile,delayRender,continueRender,cancelRender,useCurrentFrame} from 'remotion';
import * as T from 'three';
import assets from './assets.json';import ai from './ai.json';
import {GraphicTitle,Opening} from './Titles.jsx';import {CivilizationCopy} from './CivilizationCopy.jsx';
import {CinematicBridge,bridgeData} from './Bridge.jsx';import {transitionFor,reelSegments,comparisonSegments,smooth} from './transitions.js';import {ease,clamp,shots} from './story.js';import {createEngine} from './engine.js';
let promise;
function load(){return promise??=(async()=>{const loader=new T.TextureLoader(),textures={};await Promise.all(Object.entries(assets).filter(([k])=>!k.startsWith('scene')).map(async([k,m])=>{const tex=await loader.loadAsync(staticFile(m.file));tex.colorSpace=T.SRGBColorSpace;tex.anisotropy=16;tex.minFilter=T.LinearMipmapLinearFilter;tex.magFilter=T.LinearFilter;textures[k]=tex}));await Promise.all(['fire','letters','pyramid','ship','sky'].map(async key=>{const tex=await loader.loadAsync(staticFile('transitions/art/'+key+'.png'));tex.colorSpace=T.SRGBColorSpace;textures['clean_'+key]=tex}));await Promise.all([['Regular','400'],['Bold','700']].map(async([name,weight])=>{const f=new FontFace('SourceHan',`url(${staticFile('fonts/SourceHanSansCN-'+name+'.otf')})`,{weight});document.fonts.add(await f.load())}));await document.fonts.ready;return textures})()}
function useAssets(){const[tex,setTex]=useState(null),[handle]=useState(()=>delayRender('原始组件贴图与中文字体'));useEffect(()=>{let alive=true;load().then(t=>alive&&setTex(t)).catch(cancelRender);return()=>{alive=false}},[]);useLayoutEffect(()=>{if(tex)continueRender(handle)},[tex,handle]);return tex}
// Offline export must extract the exact timestamp; browser video seeking can bake stale frames into parallel renders.
function AIMedia({s,cursor=0,clip=null,frozen=false}){const media=clip?<OffthreadVideo toneMapped={false} src={staticFile(clip)} muted startFrom={frozen?s.frames-1:0} style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<Img src={staticFile('scenes/'+s.reference)} style={{width:'100%',height:'100%',objectFit:'cover'}}/>;return frozen?<Freeze frame={0}>{media}</Freeze>:<Sequence from={cursor} durationInFrames={s.frames} layout="none">{media}</Sequence>}
const handlePath=(s,edge,frame)=>staticFile(`transitions/motion/${s.id}-${edge}/${String(frame).padStart(3,'0')}.jpg`);
function MotionPlate({s,edge,frame,style={}}){return <Img src={handlePath(s,edge,frame)} style={{position:'absolute',width:1920,height:1080,maxWidth:'none',...style}}/>}
function ThreeCanvas({kind,frame,textures,bridge=null,annotations=1,approach=null}){
 const ref=useRef(),engine=useMemo(()=>createEngine(textures,assets),[textures]);useEffect(()=>()=>engine.dispose(),[engine]);
 const data=bridge?bridgeData(bridge):null,p=data?.p??0,annotationOpacity=bridge?(data.into?smooth(.85,1,p):1-smooth(0,.17,p)):annotations;
 const view=useMemo(()=>{const source=engine.render(kind,frame,annotationOpacity,data,approach);return{source,base:bridge?engine.getBaseAnchor():null}},[engine,kind,frame,bridge?.local,annotationOpacity,approach?.progress]);
 useLayoutEffect(()=>{if(!bridge){ref.current.getContext('2d').drawImage(view.source,0,0);window.hybridFrame={kind,frame};window.hybridReady=true}},[view,kind,frame]);
 return bridge?<CinematicBridge bridge={bridge} data={data} source={view.source} base={view.base}/>:<canvas ref={ref} width={RENDER_WIDTH} height={RENDER_HEIGHT} style={{width:'100%',height:'100%',position:'absolute'}}/>;
}
export function Shot({kind='purchase',sound=true}){const frame=useCurrentFrame(),tex=useAssets(),s=shots.find(s=>s.kind===kind);return <AbsoluteFill style={{background:'#0b1729'}}>{tex?<ThreeCanvas kind={kind} frame={frame} textures={tex}/>:null}{kind==='product'?<GraphicTitle mode="ending" frame={frame}/>:null}{sound?<Audio src={staticFile('audio/'+s.id+'-foley.wav')}/>:null}</AbsoluteFill>}
export function AIVisual({s,cursor=0,clip=null,frozen=false,local=0}){return <><AbsoluteFill><AIMedia s={s} cursor={cursor} clip={clip} frozen={frozen}/></AbsoluteFill>{clip?<CivilizationCopy shot={s} local={local}/>:<AbsoluteFill style={{fontFamily:'SourceHan',color:'#f6e8c8',background:'linear-gradient(transparent 65%,rgba(5,16,31,.94))',justifyContent:'flex-end',padding:'74px 88px'}}><div style={{fontSize:25,color:'#f0c97c',letterSpacing:3}}>AI 场景待生成 · 静帧占位</div><div style={{fontSize:48,fontWeight:700,marginTop:15}}>{s.id} · {s.name}</div></AbsoluteFill>}</>}
function PlainVisual({s,local,textures,cursor}){return s.kind==='intro'?<GraphicTitle frame={local}/>:s.kind==='ai'?<AIVisual s={s} local={local} cursor={cursor} clip={ai[s.id]?.file}/>:<>{textures?<ThreeCanvas kind={s.kind} frame={local} textures={textures}/>:null}{s.kind==='product'?<GraphicTitle mode="ending" frame={local}/>:null}</>}
function Join({a,b,transition,phase,frame,boundary,textures}){
 const p=phase/(transition.frames-1),localA=Math.min(a.frames-1,Math.max(0,frame-(boundary-a.frames))),localB=Math.max(0,frame-boundary);
 if(transition.type==='into')return <>{textures?<ThreeCanvas kind={b.kind} frame={localB} textures={textures} bridge={{...transition,local:phase,s:a}}/>:null}<CivilizationCopy shot={a} local={localA} opacity={1-smooth(0,.13,p)}/>{b.kind==='product'?<GraphicTitle mode="ending" frame={localB}/>:null}</>;
 if(transition.type==='out')return <>{textures?<ThreeCanvas kind={a.kind} frame={localA} textures={textures} bridge={{...transition,local:phase,s:b}}/>:null}<CivilizationCopy shot={b} local={localB} opacity={smooth(.86,1,p)}/></>;
 const approachConfig=transition.approach??{key:transition.type==='paper'?'weave':'pyramid',uv:[.48,.20],zoom:transition.type==='paper'?4:3.5,range:[0,.96]};
 const old=a.kind==='ai'?<MotionPlate s={a} edge="tail" frame={phase}/>:['paper','material'].includes(transition.type)&&textures?<ThreeCanvas kind={a.kind} frame={localA} textures={textures} annotations={1-smooth(0,.18,p)} approach={{...approachConfig,progress:smooth(...approachConfig.range,p),previousProgress:Array.from({length:8},(_,i)=>smooth(...approachConfig.range,Math.max(0,p-.5*i/7/(transition.frames-1))))}}/>:<PlainVisual s={a} local={localA} textures={textures}/>,next=b.kind==='ai'?<MotionPlate s={b} edge="head" frame={transition.handleFrames?Math.round(phase*(transition.handleFrames-1)/(transition.frames-1)):phase}/>:<PlainVisual s={b} local={localB} textures={textures}/>;
 const [fx,fy]=transition.focus??[960,540],q=transition.reveal?smooth(...transition.reveal,p):transition.type==='paper'?smooth(.40,.89,p):transition.type==='material'?smooth(.25,.89,p):smooth(.07,.93,p);
 // Short spatial reveals: only a narrow moving boundary overlaps the two worlds.
 const mask=transition.type==='mist'?`linear-gradient(145deg,#000 ${q*155-40}%,transparent ${q*155-18}%)`:transition.type==='paper'?`radial-gradient(ellipse at ${fx/19.2}% ${fy/10.8}%,#000 ${q*155-12}%,transparent ${q*155+2}%)`:`radial-gradient(ellipse at ${fx/19.2}% ${fy/10.8}%,#000 ${q*150-15}%,transparent ${q*150+5}%)`;
 const light=transition.type==='light';
 const mistSVG=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1920 1080"><defs><filter id="fog"><feTurbulence baseFrequency=".004 .007" numOctaves="3" seed="37"/><feDisplacementMap in="SourceGraphic" scale="110"/><feGaussianBlur stdDeviation="22"/></filter></defs><path d="M-400 -200 H${q*3800-500} L${q*3800-1500} 1280 H-400Z" fill="white" filter="url(#fog)"/></svg>`;
 const spatialMask=transition.type==='mist'?`url("data:image/svg+xml,${encodeURIComponent(mistSVG)}")`:mask;
 return <><AbsoluteFill style={light?{opacity:1-smooth(.02,.48,p)}:{}}>{old}</AbsoluteFill><AbsoluteFill style={light?{opacity:smooth(.18,.88,p)}:{maskImage:spatialMask,WebkitMaskImage:spatialMask,maskSize:'100% 100%',WebkitMaskSize:'100% 100%'}}>{next}</AbsoluteFill>{light?<AbsoluteFill style={{background:`radial-gradient(circle at ${50+(fx/19.2-50)*q}% ${44+(fy/10.8-44)*q}%,rgba(242,173,65,.36),transparent ${24-19*q}%)`,opacity:Math.sin(p*Math.PI)}}/>:null}{a.kind==='ai'?<CivilizationCopy shot={a} local={localA} opacity={1-smooth(0,.17,p)}/>:null}{b.kind==='ai'?<CivilizationCopy shot={b} local={localB} opacity={smooth(.85,1,p)}/>:null}</>;
}
export function Movie({selection='all',sound=true}){
 const frame=useCurrentFrame(),tex=useAssets(),raw=selection==='pilot'?shots.filter(s=>s.id==='02'||s.id==='08'):shots;
 let n=0;const list=raw.map(s=>{const x={...s,start:n};n+=s.frames;return x});let join=null;
 for(let i=1;i<list.length;i++){const b=list[i],a=list[i-1],transition=transitionFor(a,b);if(frame>=b.start-transition.pre&&frame<b.start+transition.post){join={a,b,transition,phase:frame-(b.start-transition.pre),boundary:b.start};break}}
 const s=list.find(s=>frame>=s.start&&frame<s.start+s.frames)||list.at(-1);
 return <AbsoluteFill style={{background:'#0b1729'}}>{join?<Join {...join} frame={frame} textures={tex}/>:<PlainVisual s={s} local={frame-s.start} cursor={s.start} textures={tex}/>} {sound?<Audio src={staticFile('audio/'+(selection==='pilot'?'pilot':'master')+'.wav')}/>:null}</AbsoluteFill>
}
export function TransitionDemo(){return <Sequence from={-261}><Movie/></Sequence>}
export function TransitionReel(){return <>{reelSegments.map((seg,i)=>{const[a,b]=seg.join.pair.split('-').map(id=>shots.find(s=>s.id===id));return <Sequence key={b.id} from={seg.from} durationInFrames={seg.frames}><Sequence from={-(b.start-seg.join.pre-15)}><Movie/></Sequence><div style={{position:'absolute',top:24,left:30,fontFamily:'SourceHan',fontSize:21,color:'#f6e4bc',background:'rgba(4,14,25,.78)',padding:'9px 16px'}}>衔接 {i+1} / 11 · {a.name} → {b.name}</div></Sequence>})}</>}
export function FeatureCompare(){return <AbsoluteFill style={{background:'#08121e'}}>{comparisonSegments.map(seg=>{const b=shots.find(s=>s.id===seg.join.pair.split('-')[1]),start=b.start-seg.join.pre-15;return <Sequence key={b.id} from={seg.from} durationInFrames={seg.frames}><div style={{position:'absolute',left:0,top:240,width:960,height:540,overflow:'hidden'}}><Sequence from={-start}><OffthreadVideo toneMapped={false} src={staticFile('review/before.mp4')} muted style={{width:'100%',height:'100%'}}/></Sequence></div><div style={{position:'absolute',left:960,top:240,width:1920,height:1080,transform:'scale(.5)',transformOrigin:'top left'}}><Sequence from={-start}><Movie/></Sequence></div><div style={{position:'absolute',top:140,left:80,color:'#e7d6b4',fontFamily:'SourceHan',fontSize:42}}>精修前</div><div style={{position:'absolute',top:140,left:1040,color:'#e7d6b4',fontFamily:'SourceHan',fontSize:42}}>精修后 · {seg.join.pair}</div></Sequence>})}</AbsoluteFill>}
