import React,{useEffect,useState} from 'react';import {AbsoluteFill,Audio,staticFile,delayRender,continueRender,cancelRender,useCurrentFrame} from 'remotion';import {clamp,ease} from './story.js';
let fontPromise;
function useTitleFonts(){const[ready,setReady]=useState(false);const[h]=useState(()=>delayRender('片头片尾字体'));useEffect(()=>{fontPromise??=Promise.all([['Regular','400'],['Bold','700']].map(async([n,w])=>{const font=new FontFace('SourceHan',`url(${staticFile('fonts/SourceHanSansCN-'+n+'.otf')})`,{weight:w});document.fonts.add(await font.load())}));fontPromise.then(()=>{setReady(true);continueRender(h)}).catch(cancelRender)},[h]);return ready;}
const gold='#ead39f',cream='#f6ecd4';
export const ENDING={main:'文明的下一章，由你开创',tagline:'从第一簇火光，到无垠星海',mainStart:33,mainEnd:45,taglineStart:42,taglineEnd:54};
const fade=(frame,start,span)=>ease(clamp((frame-start)/span));
function opticalOffset(text,size,weight,spacing,ready){if(!ready||typeof document==='undefined')return 0;const ctx=document.createElement('canvas').getContext('2d');ctx.font=`${weight} ${size}px SourceHan`;const m=ctx.measureText(text),advance=m.width+spacing*text.length,inkLeft=-m.actualBoundingBoxLeft,inkRight=m.actualBoundingBoxRight+spacing*(text.length-1);return advance/2-(inkLeft+inkRight)/2;}
export function GraphicTitle({mode='opening',frame:provided}){
 const ready=useTitleFonts();const current=useCurrentFrame(),f=provided??current,opening=mode==='opening',reveal=fade(f,opening?12:20,opening?28:25),details=fade(f,opening?35:38,22);
 if(!opening)return <AbsoluteFill style={{fontFamily:'SourceHan',color:cream,pointerEvents:'none',overflow:'hidden'}}>
  <AbsoluteFill style={{opacity:fade(f,22,11),background:'radial-gradient(ellipse 72% 40% at 50% 51%,rgba(3,12,23,.80) 0%,rgba(3,12,23,.50) 48%,rgba(3,12,23,.10) 100%),linear-gradient(0deg,rgba(3,12,23,.38),transparent 35%,rgba(3,12,23,.53))'}}/>
  <div style={{position:'absolute',top:139,width:'100%',textAlign:'center',opacity:fade(f,33,12),textShadow:'0 3px 18px #08121d'}}><div style={{fontSize:70,fontWeight:700,letterSpacing:16,paddingLeft:16,color:gold}}>更迭</div><div style={{fontSize:23,letterSpacing:12,paddingLeft:12,marginTop:4}}>ITERATION</div><div style={{fontSize:24,letterSpacing:4,marginTop:22}}>科技史策略桌游</div></div>
  <div style={{position:'absolute',left:960+opticalOffset(ENDING.main,84,700,0,ready),top:540,transform:'translate(-50%,-50%)',whiteSpace:'nowrap',textAlign:'center',fontSize:84,lineHeight:1.35,fontWeight:700,color:gold,textShadow:'0 3px 24px rgba(0,0,0,.65)',opacity:fade(f,ENDING.mainStart,ENDING.mainEnd-ENDING.mainStart)}}>{ENDING.main}</div>
  <div style={{position:'absolute',left:960+opticalOffset(ENDING.tagline,32,400,3,ready),top:650,transform:'translate(-50%,-50%)',whiteSpace:'nowrap',textAlign:'center',fontSize:32,lineHeight:1.4,letterSpacing:3,color:'#e2d9c8',textShadow:'0 2px 14px #030c17',opacity:fade(f,ENDING.taglineStart,ENDING.taglineEnd-ENDING.taglineStart)}}>{ENDING.tagline}</div>
 </AbsoluteFill>;
 const stars=Array.from({length:62},(_,i)=>({x:((i*367+179)%1800)+60,y:((i*i*73+137)%940)+70,r:i%5===0?2.1:1,opacity:.12+(i%7)*.04}));
 return <AbsoluteFill style={{fontFamily:'SourceHan',overflow:'hidden',color:cream,pointerEvents:'none',opacity:opening?1:fade(f,0,24)}}>
  <AbsoluteFill style={{background:opening?'radial-gradient(ellipse at 50% 48%,#243d53 0%,#102337 42%,#071422 100%)':'linear-gradient(0deg,rgba(5,17,30,.97),rgba(5,17,30,.1) 52%,rgba(5,17,30,.94))'}}/>
  <svg viewBox="0 0 1920 1080" style={{position:'absolute',width:'100%',height:'100%'}}>
   <defs><filter id={'paper-'+mode}><feTurbulence type="fractalNoise" baseFrequency=".48" numOctaves="3" seed="23"/><feColorMatrix type="saturate" values="0"/></filter><radialGradient id={'glow-'+mode}><stop stopColor="#dfbd75" stopOpacity=".18"/><stop offset="1" stopColor="#dfbd75" stopOpacity="0"/></radialGradient></defs>
   <rect width="1920" height="1080" filter={`url(#paper-${mode})`} opacity={opening?.07:.035}/>
   {stars.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r={p.r} fill={gold} opacity={p.opacity*(opening?1:.5)}/>)}
   {opening?<g transform={`translate(960 475) rotate(${-8+f*.018})`} opacity={fade(f,0,22)}><circle r="395" fill={`url(#glow-${mode})`}/>{[246,263,350].map((r,i)=><circle key={r} r={r} fill="none" stroke={gold} strokeWidth={i===1?1.5:.7} opacity={i===1?.45:.19} strokeDasharray={2*Math.PI*r} strokeDashoffset={2*Math.PI*r*(1-fade(f,i*6,52))}/>)}{Array.from({length:16},(_,i)=>{const a=i*Math.PI/8;return <g key={i}><line x1={Math.cos(a)*275} y1={Math.sin(a)*275} x2={Math.cos(a)*286} y2={Math.sin(a)*286} stroke={gold} opacity=".5"/><circle cx={Math.cos(a)*350} cy={Math.sin(a)*350} r={i%4?2:4} fill={gold} opacity=".6"/></g>})}</g>:null}
   <path d={opening?'M260 910 H810 L840 895 H1080 L1110 910 H1660':'M250 910 H780 L810 895 H1110 L1140 910 H1670'} stroke={gold} fill="none" opacity={details*.5}/>
   <path d="M90 220 V90 H340 M1580 90 H1830 V220 M90 860 V990 H340 M1580 990 H1830 V860" stroke={gold} strokeWidth="1" fill="none" opacity={details*.32}/>
  </svg>
  {opening?<div style={{position:'absolute',top:318,left:0,width:'100%',textAlign:'center',opacity:reveal,transform:`translateY(${(1-reveal)*18}px)`}}><div style={{fontSize:137,fontWeight:700,letterSpacing:30,paddingLeft:30,color:gold,textShadow:'0 4px 30px #08121d'}}>更迭</div><div style={{fontSize:28,letterSpacing:20,paddingLeft:20,marginTop:12}}>ITERATION</div><div style={{fontSize:29,letterSpacing:5,marginTop:52,opacity:details}}>科技史策略桌游</div></div>:<div style={{position:'absolute',top:92,left:0,width:'100%',textAlign:'center',opacity:reveal,transform:`translateY(${(1-reveal)*12}px)`}}><div style={{fontSize:100,fontWeight:700,letterSpacing:19,paddingLeft:19,color:gold}}>更迭</div><div style={{fontSize:24,letterSpacing:13,paddingLeft:13,marginTop:5}}>ITERATION</div><div style={{fontSize:26,letterSpacing:4,marginTop:25}}>科技史策略桌游</div></div>}
  <div style={{position:'absolute',left:0,bottom:opening?126:111,width:'100%',textAlign:'center',opacity:details}}><div style={{fontSize:opening?26:43,fontWeight:opening?400:700,letterSpacing:opening?4:3,color:opening?'#bdc9cf':gold}}>{opening?'资源配置 · 科技积累 · 奇观竞逐 · 未来挑战':'文明的下一章，由你开创'}</div>{!opening?<div style={{fontSize:25,marginTop:23,color:'#c0ccd5'}}>从第一簇火光，到无垠星海</div>:null}</div>
 </AbsoluteFill>
}
export function Opening({sound=false}){return <><GraphicTitle/>{sound?<Audio src={staticFile('audio/00-foley.wav')}/>:null}</>}
