import fs from 'node:fs';import path from 'node:path';import {execFileSync} from 'node:child_process';import {bundle} from '@remotion/bundler';import {openBrowser,selectComposition,renderStill} from '@remotion/renderer';
const root=path.resolve(import.meta.dirname,'..'),python=path.resolve(root,'../工具/.venv/bin/python'),fixture=path.join(root,'public/qa-fixture'),entry=path.join(root,'tools/.qa-entry.jsx'),original=fs.readFileSync(path.join(root,'src/ai.json'));
fs.mkdirSync(fixture,{recursive:true});let browser;
try{
 const ffmpeg=execFileSync(python,['-c','import imageio_ffmpeg;print(imageio_ffmpeg.get_ffmpeg_exe())'],{encoding:'utf8'}).trim();
 execFileSync(ffmpeg,['-v','error','-y','-f','lavfi','-i','color=c=red:s=160x90:r=30:d=1','-f','lavfi','-i','color=c=blue:s=160x90:r=30:d=1','-filter_complex','[0:v][1:v]concat=n=2:v=1:a=0[out]','-map','[out]','-c:v','libx264','-pix_fmt','yuv420p',path.join(fixture,'timing.mp4')]);
 fs.writeFileSync(entry,`import React from 'react';import {Composition,registerRoot} from 'remotion';import {AIVisual} from '../src/Movie.jsx';const s={id:'08',frames:60,seconds:2,reference:'BG-08-FAST.png'};function Test(p){return <AIVisual s={s} cursor={60} clip="qa-fixture/timing.mp4" {...p}/>};registerRoot(()=> <><Composition id="Timing" component={Test} durationInFrames={120} fps={30} width={1920} height={1080}/><Composition id="Frozen" component={Test} defaultProps={{frozen:true}} durationInFrames={120} fps={30} width={1920} height={1080}/></>);`);
 const serveUrl=await bundle({entryPoint:entry,publicDir:path.join(root,'public'),outDir:path.join(root,'.cache/timing-bundle')}),browserExecutable='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',chromiumOptions={gl:'angle'};browser=await openBrowser('chrome',{browserExecutable,chromiumOptions});const base={serveUrl,browserExecutable,chromiumOptions,puppeteerInstance:browser,timeoutInMilliseconds:120000};
 for(const[id,frame,file]of [['Timing',60,'red.png'],['Timing',90,'blue.png'],['Frozen',100,'frozen.png']]){const c=await selectComposition({...base,id});await renderStill({...base,composition:c,frame,output:path.join(fixture,file),imageFormat:'png'});}
 const pixels=JSON.parse(execFileSync(python,['-c',`from PIL import Image;import json;from pathlib import Path;p=Path(${JSON.stringify(fixture)});print(json.dumps({n:Image.open(p/n).getpixel((960,540))[:3]for n in ['red.png','blue.png','frozen.png']}))`],{encoding:'utf8'}));
 if(!(pixels['red.png'][0]>200&&pixels['red.png'][2]<30&&pixels['blue.png'][2]>200&&pixels['frozen.png'][2]>200))throw new Error(JSON.stringify(pixels));if(!original.equals(fs.readFileSync(path.join(root,'src/ai.json'))))throw new Error('Real manifest changed');fs.writeFileSync(path.join(root,'记录/AI播放起点核对.json'),JSON.stringify({passed:true,scope:'Disposable red/blue video: global frame60 is local0 red; global90 is local30 blue; frozen previous clip uses final blue frame. Real AI manifest unchanged.',pixels},null,2)+'\n');console.log('AI timing and frozen last frame passed');
}finally{await browser?.close({silent:true});fs.rmSync(fixture,{recursive:true,force:true});fs.rmSync(entry,{force:true})}
