import {shots} from '../src/story.js';import {bundle} from '@remotion/bundler';import {selectComposition,renderMedia,renderStill,openBrowser,makeCancelSignal} from '@remotion/renderer';import fs from 'node:fs';import crypto from 'node:crypto';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');process.chdir(root);const task=process.argv[2]||'stills';
const url=await bundle({entryPoint:path.join(root,'src/Root.jsx'),publicDir:path.join(root,'public'),outDir:path.join(root,['repeat','endingproof','copyproof','firecopy','latestcopy'].includes(task)?'.cache/bundle-'+task:'.cache/bundle')});if(task==='bundle')process.exit(0);
const chromiumOptions={gl:'angle'},browserExecutable='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';const browser=await openBrowser('chrome',{browserExecutable,chromiumOptions});
const {cancelSignal,cancel}=makeCancelSignal();process.once('SIGINT',cancel);process.once('SIGTERM',cancel);fs.mkdirSync(path.join(root,'.cache'),{recursive:true});const pidFile=path.join(root,'.cache','renderer-'+task+'.pid');fs.writeFileSync(pidFile,String(process.pid));
try{const base={cancelSignal,serveUrl:url,browserExecutable,chromiumOptions,puppeteerInstance:browser,timeoutInMilliseconds:120000,logLevel:'warn',scale:2};
 if(task==='latestcopy'){const c=await selectComposition({...base,id:'Hybrid'});await renderStill({...base,composition:c,frame:1850,output:path.join(root,'记录/宣传语修订-FAST.png'),imageFormat:'png'});console.log('FAST chapter proof saved')}
 if(task==='firecopy'){const c=await selectComposition({...base,id:'Hybrid'});for(const [name,frame] of [['火光',190],['金字塔',1170],['奇观',1410]])await renderStill({...base,composition:c,frame,output:path.join(root,'记录/宣传语修订-'+name+'.png'),imageFormat:'png'});console.log('Latest copy proofs saved')}
 if(task==='copy'||task==='copyproof'){const c=await selectComposition({...base,id:'Hybrid'});for(const [name,frame]of [['火光',190],['知识',735],['专利',950],['金字塔',1170],['奇观',1410],['工业',1685],['FAST',1850],['挑战',2220],['星海',2460],['片头',90],['片尾',2640]])await renderStill({...base,composition:c,frame,output:path.join(root,'记录/宣传语修订-'+name+'.png'),imageFormat:'png'});console.log('Copy proofs saved');if(task==='copyproof')process.exitCode=0;}
 if(task==='copyproof'){}
 else
 if(task==='cadence'){const c=await selectComposition({...base,id:'Hybrid'});await renderMedia({...base,composition:c,outputLocation:path.join(root,'输出/画质增强/4K火光-采帧修复验证.mp4'),frameRange:[150,239],codec:'h264',crf:16,pixelFormat:'yuv420p',audioCodec:'aac',audioBitrate:'256k',concurrency:3,onProgress:p=>console.log('Cadence',Math.round(p.progress*100)+'%')});console.log('Cadence sample rendered')}
 else if(task==='fourkproof'){for(const[id,frame]of [['Shot02',145],['Shot06',120],['Shot11',90]]){const c=await selectComposition({...base,id});await renderStill({...base,composition:c,frame,output:path.join(root,`记录/4K-${id}-${frame}.png`),imageFormat:'png'});console.log('4K proof',id,frame)}}
 else if(task==='materials'){for(const[id,frames]of [['Shot02',[0,75,106,145,255,345]],['Shot04',[156,240]],['Shot06',[120,220]],['Shot09',[195,285]],['Shot11',[32,33,42,45,54,90,149]],['Calibration',[0]]]){const c=await selectComposition({...base,id});for(const frame of frames){await renderStill({...base,composition:c,frame,output:path.join(root,`记录/材质精修-${id}-${frame}.png`),imageFormat:'png'});console.log('Material',id,frame)}}}
 else if(task==='placement'){for(const[id,frames]of [['Shot02',[0,145,255,345]],['Shot04',[240]],['Shot06',[15,120,220,315]],['Shot09',[285]],['Shot11',[60]],['Calibration',[0]]]){const c=await selectComposition({...base,id});for(const frame of frames){await renderStill({...base,composition:c,frame,output:path.join(root,`记录/牌位修正-${id}-${frame}.png`),imageFormat:'png'});console.log('Placement',id,frame)}}}
 else if(task==='endingstills'){const c=await selectComposition({...base,id:'Shot11'});for(const frame of [32,33,42,45,54,90,149]){await renderStill({...base,composition:c,frame,output:path.join(root,`记录/材质精修-Shot11-${frame}.png`),imageFormat:'png'});console.log('Ending still',frame)}}
 else if(task==='endingproof'){const full=await selectComposition({...base,id:'Hybrid'}),ending=await selectComposition({...base,id:'Shot11'});for(const frame of [2582,2583,2592,2595,2604,2640]){await renderStill({...base,composition:full,frame,output:path.join(root,`记录/片尾同步-Hybrid-${frame}.png`),imageFormat:'png'});console.log('Ending full',frame)}await renderStill({...base,composition:ending,frame:90,output:path.join(root,'记录/片尾同步-Shot11-90.png'),imageFormat:'png'});const files=['片尾同步-Hybrid-2640.png','片尾同步-Shot11-90.png'],hashes=files.map(f=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'记录',f))).digest('hex'));fs.writeFileSync(path.join(root,'记录/整片与独立片尾同步.json'),JSON.stringify({fullFrame:2640,localFrame:90,hashes,identical:hashes[0]===hashes[1]},null,2));if(hashes[0]!==hashes[1])throw new Error('Ending mismatch');console.log('Ending synchronized pixel-for-pixel');}
 else if(task==='repeat'){const c=await selectComposition({...base,id:'Hybrid'}),files=['RepeatBridgeA.png','RepeatBridgeB.png'];for(const file of files)await renderStill({...base,composition:c,frame:2385,output:path.join(root,'记录',file),imageFormat:'png'});const hashes=files.map(f=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'记录',f))).digest('hex'));fs.writeFileSync(path.join(root,'记录/转场同帧重复渲染.json'),JSON.stringify({frame:2385,hashes,identical:hashes[0]===hashes[1]},null,2));if(hashes[0]!==hashes[1])throw new Error('Bridge repeat mismatch');console.log('Repeated bridge frame identical');}
 else if(task==='proof'){const c=await selectComposition({...base,id:'Hybrid'});for(const frame of [276,288,300,312,323,1266,1278,1290,1305,1319,2340,2355,2370,2385,2400,2411]){await renderStill({...base,composition:c,frame,output:path.join(root,`记录/精修-${frame}.png`),imageFormat:'png'});console.log('Proof',frame)}}
 else if(task==='edges'){const c=await selectComposition({...base,id:'Hybrid'});for(const frame of [2344,2345,2346,2347,2524,2525,2526,2527]){await renderStill({...base,composition:c,frame,output:path.join(root,`记录/修正边界-${frame}.png`),imageFormat:'png'});console.log('Edge',frame)}}
 else if(task==='revision'){const c=await selectComposition({...base,id:'Hybrid'});for(const frame of [210,750,1200,1695,1920,2460,276,288,300,312,330,341,1266,1290,1310,1331,1410,2330,2346,2370,2390,2411,2570,2591,2610]){await renderStill({...base,composition:c,frame,output:path.join(root,`记录/修订-${frame}.png`),imageFormat:'png'});console.log('Revision',frame)}const cal=await selectComposition({...base,id:'Calibration'});await renderStill({...base,composition:cal,frame:0,output:path.join(root,'记录/Calibration-0.png'),imageFormat:'png'});}
 else if(task==='transitions'){const c=await selectComposition({...base,id:'Hybrid'}),edit=JSON.parse(fs.readFileSync('src/edit.json'));for(const j of edit.joins){const b=shots.find(s=>s.id===j.pair.split('-')[1]);for(const phase of [0,.2,.4,.6,.8,1]){const frame=b.start-j.pre+Math.round(phase*(j.pre+j.post-1));await renderStill({...base,composition:c,frame,output:path.join(root,`记录/精修全段-${j.pair}-${Math.round(phase*100)}.png`),imageFormat:'png'});console.log('Transition',j.pair,frame)}}const files=['RepeatBridgeA.png','RepeatBridgeB.png'];for(const file of files)await renderStill({...base,composition:c,frame:2385,output:path.join(root,'记录',file),imageFormat:'png'});const hashes=files.map(f=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'记录',f))).digest('hex'));fs.writeFileSync(path.join(root,'记录/转场同帧重复渲染.json'),JSON.stringify({frame:2385,hashes,identical:hashes[0]===hashes[1]},null,2));if(hashes[0]!==hashes[1])throw new Error('Bridge repeat mismatch');}
 else if(task==='stills'){for(const[id,frames]of [['Shot02',[0,75,145,255,345]],['Shot04',[45,156,240]],['Shot06',[15,120,220,315]],['Shot09',[55,195,285]],['Shot11',[60]],['Calibration',[0]],['Opening',[0,45,90,119]]]){const c=await selectComposition({...base,id});for(const frame of frames){await renderStill({...base,composition:c,frame,output:path.join(root,`记录/${id}-${frame}.png`),imageFormat:'png'});console.log(id,frame)}}const c=await selectComposition({...base,id:'Hybrid'});for(const[id,frame]of [['01',150],['03',690],['05',1140],['07',1650],['08',1800],['10',2400]]){await renderStill({...base,composition:c,frame,output:path.join(root,`记录/Placeholder${id}.png`),imageFormat:'png'});console.log('Placeholder',id)}const proof=await selectComposition({...base,id:'Shot09'}),proofFiles=['RepeatA.png','RepeatB.png'];for(const file of proofFiles)await renderStill({...base,composition:proof,frame:195,output:path.join(root,'记录',file),imageFormat:'png'});const hashes=proofFiles.map(file=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'记录',file))).digest('hex'));fs.writeFileSync(path.join(root,'记录/同帧重复渲染.json'),JSON.stringify({frame:195,composition:'Shot09',hashes,identical:hashes[0]===hashes[1]},null,2)+'\n');if(hashes[0]!==hashes[1])throw new Error('Repeated frame mismatch');}
 else{const ids=task==='latestcopy'?['Hybrid','Pilot','TransitionReel','TransitionDemo','FeatureCompare','Shot06']:task==='firecopy'?['Hybrid','TransitionReel','TransitionDemo','FeatureCompare','Shot06']:task==='final'?['Opening','Hybrid','TransitionReel','FeatureCompare','TransitionDemo','Pilot','Shot02','Shot04','Shot06','Shot09','Shot11']:task==='finish'?['Hybrid','TransitionReel','Shot11']:task==='edits'?['Opening','Hybrid','Pilot','TransitionReel','TransitionDemo','FeatureCompare']:task==='copy'?['Opening','Hybrid','Pilot','TransitionReel','TransitionDemo','FeatureCompare','Shot02','Shot04','Shot06','Shot09','Shot11']:task==='pilot'?['Pilot']:task==='movie'?['Hybrid']:task==='titles'?['Opening','Shot11']:task==='corrected'?['Opening','Shot09','Shot11','TransitionDemo']:process.argv[3]?[process.argv[3]]:['Shot02','Shot04','Shot06','Shot09','Shot11'];for(const id of ids){const c=await selectComposition({...base,id}),output=path.join(root,'输出',id+'.mp4');let last=-1;await renderMedia({...base,composition:c,outputLocation:output,codec:'h264',crf:16,pixelFormat:'yuv420p',audioCodec:'aac',audioBitrate:'256k',concurrency:3,onProgress:p=>{const pct=Math.floor(p.progress*10)*10;if(pct!==last){last=pct;console.log(id,pct+'%')}}});console.log('Saved '+id)}}
}finally{await browser.close({silent:true});if(fs.existsSync(pidFile)&&fs.readFileSync(pidFile,'utf8')===String(process.pid))fs.rmSync(pidFile)}
